# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
loom_version=1.15-SNAPSHOT
mixin_version=0.17.2+mixin.0.8.7
loader_version=0.19.2

# Mod Properties
mod_version=1.0.0
maven_group=xyz.nekomilky.mcmod.statsscoreboard
