pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'stats-scoreboard'

// add all projects
file('versions').eachDir { dir ->
    include ":${dir.name}"
    project(":${dir.name}").projectDir = dir
}
